name: Run IPO Agent Daily

on:
  workflow_dispatch: # Déclenché en externe par cron-job.org

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests html2text anthropic python-dotenv supabase postgrest

    - name: Executer l'Agent IA
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SUPABASE_URL: "https://pothhxmdapkoctoygtcs.supabase.co"
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python main.py